name: Github Actions Demo
on:
  push:
    branches:
      - master
jobs:
  echo-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        env:
          USERNAME: zhaosi
        run: |
          echo $USERNAME Hello World!
